### ISSUE TITLE
Is it possible to swap flate2 with libflate?

### ISSUE THREAD

**Issue by kosinix** [lgvz/imagefmt#2]
Is it possible for imagefmt to switch to a pure Rust implementation of DEFLATE: [https://github.com/sile/libflate](https://github.com/sile/libflate) ?

**Comment by lgvz** [comment]
Not soon. Flate2 is nearly twice as fast to decode and it relies on the better tested miniz library. That libflate is very recent and probably buggier.

**Comment by kosinix** [comment]
You are very much correct! I'm currently experiencing problems with latest version of image and image-png maybe because of the recent swap to libflate.

**Comment by kosinix** [comment]
I feel so stupid. Im actually referring to rust deflate not libflate. Anyways, moving to close this issue.
