### ISSUE TITLE
The future of this library

### ISSUE THREAD

**Issue by vitvakatu** [lgvz/imagefmt#3]
Hello, @lgvz, thank you for this library. 
I was looking for a convenient and compact solution for reading and writing images, and I seem to have found exactly what I was looking for. However, I noticed that the repository has not been updated for a long time.
What are your plans? Is this project abandoned? Or are there any features planned, such as full support for the jpeg format?

**Comment by lgvz** [comment]
I was going to work on jpeg but other things came up and I don't think I can work on this anymore.

If someone else implemented it, I could possibly assist lightly and merge it (and I'd be an "asshole" about it and not accept anything that I'd not happen to like). Or someone could fork.

**Comment by vitvakatu** [comment]
Well, I'm going to try it, if I have enough time.

**Comment by lgvz** [comment]
Cool... usually people only wish for things. Hope you'll find the time.
